services:
  backend-app:
    container_name: avtodiva-backend
    build: .
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:postgresql://${DB_HOST}:${DB_DOCKER_PORT}/${DB_NAME}${DB_PARAMS}",
        "spring.datasource.username" : "${DB_USERNAME}",
        "spring.datasource.password" : "${DB_PASSWORD}",
        "spring.liquibase.change-log" : "classpath:db/changelog/db.changelog-master.yaml",
        "spring.jpa.hibernate.ddl-auto" : "validate",
        "spring.jpa.open-in-view" : "false",
        "jwt.secret" : "${JWT_SECRET}",
        "jwt.expiration" : "${JWT_EXPIRATION}",
        "spring.jpa.show-sql" : "false",
        "spring.jpa.properties.hibernate.show_sql" : "false",
        "spring.jpa.properties.hibernate.format_sql" : "false",
        "logging.level.org.hibernate.SQL" : "OFF",
        "logging.level.org.hibernate.stat" : "DEBUG",
        "spring.jpa.properties.hibernate.jdbc.batch_size" : "${BATCH_SIZE}",
        "spring.jpa.properties.hibernate.order_inserts" : "true",
        "spring.jpa.properties.hibernate.order_updates" : "true",
        "spring.jpa.properties.hibernate.generate_statistics" : "true",
      }'