services:
  backend-app:
    restart: unless-stopped
    container_name: avtodiva-backend
    image: andreypolezhaiev/avtodiva-backend:latest
    env_file:
      - .env
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
    networks:
      - avtodiva-net
    environment:
      - SPRING_PROFILES_ACTIVE=dev

networks:
  avtodiva-net:
    external: true
    name: avtodiva-network